### ISSUE TITLE
Wrong employees parameter definition in oa3 yaml

### ISSUE THREAD

**Issue by brannow** [personio/api-docs#29]
the requests for
`/company/attendances:`
`/company/time-offs:`
define the employees parameter in query (as comma list)

the server denied such format with the message "the employees must be an array"

after some try and error, the personio server accepted a body json object with an integer array (or an empty array as well)
the response data matched also the expected result, so I assume the documentation is not up to date.

Here the changes:
```yaml
- name: employees
  in: query
  required: false
  description: A list of Personio employee ID's to filter the results. The result filters including only absences of provided employees
  explode: true
  schema:
    type: array
    items:
      type: integer
```
to
```yaml
- name: employees
  in: body
  required: false
  description: A list of Personio employee ID's to filter the results. The result filters including only absences of provided employees
  explode: true
  schema:
  type: object
  properties:
    employees:
      type: array
      items:
        type: integer
```
